/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlpersonal;

/**
 *
 * @author Jonas
 */
public class ventanaPrueba extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrueba
     */
    public ventanaPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Opc1 = new javax.swing.JRadioButton();
        Opc2 = new javax.swing.JRadioButton();
        Opc3 = new javax.swing.JRadioButton();
        Opc5 = new javax.swing.JRadioButton();
        Opc4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Opc6 = new javax.swing.JRadioButton();
        Opc7 = new javax.swing.JRadioButton();
        Opc8 = new javax.swing.JRadioButton();
        Opc9 = new javax.swing.JRadioButton();
        Opc10 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Opc11 = new javax.swing.JRadioButton();
        Opc12 = new javax.swing.JRadioButton();
        Opc13 = new javax.swing.JRadioButton();
        Opc14 = new javax.swing.JRadioButton();
        Opc15 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Opc16 = new javax.swing.JRadioButton();
        Opc17 = new javax.swing.JRadioButton();
        Opc18 = new javax.swing.JRadioButton();
        Opc19 = new javax.swing.JRadioButton();
        Opc20 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Opc21 = new javax.swing.JRadioButton();
        Opc22 = new javax.swing.JRadioButton();
        Opc23 = new javax.swing.JRadioButton();
        Opc24 = new javax.swing.JRadioButton();
        Opc25 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Opc26 = new javax.swing.JRadioButton();
        Opc27 = new javax.swing.JRadioButton();
        Opc28 = new javax.swing.JRadioButton();
        Opc29 = new javax.swing.JRadioButton();
        Opc30 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Opc31 = new javax.swing.JRadioButton();
        Opc32 = new javax.swing.JRadioButton();
        Opc33 = new javax.swing.JRadioButton();
        Opc34 = new javax.swing.JRadioButton();
        Opc35 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Opc36 = new javax.swing.JRadioButton();
        Opc37 = new javax.swing.JRadioButton();
        Opc38 = new javax.swing.JRadioButton();
        Opc39 = new javax.swing.JRadioButton();
        Opc40 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Opc41 = new javax.swing.JRadioButton();
        Opc42 = new javax.swing.JRadioButton();
        Opc43 = new javax.swing.JRadioButton();
        Opc44 = new javax.swing.JRadioButton();
        Opc45 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Opc46 = new javax.swing.JRadioButton();
        Opc47 = new javax.swing.JRadioButton();
        Opc48 = new javax.swing.JRadioButton();
        Opc49 = new javax.swing.JRadioButton();
        Opc50 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        Opc51 = new javax.swing.JRadioButton();
        Opc52 = new javax.swing.JRadioButton();
        Opc53 = new javax.swing.JRadioButton();
        Opc54 = new javax.swing.JRadioButton();
        Opc55 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        Opc56 = new javax.swing.JRadioButton();
        Opc57 = new javax.swing.JRadioButton();
        Opc58 = new javax.swing.JRadioButton();
        Opc59 = new javax.swing.JRadioButton();
        Opc60 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        Opc61 = new javax.swing.JRadioButton();
        Opc62 = new javax.swing.JRadioButton();
        Opc63 = new javax.swing.JRadioButton();
        Opc64 = new javax.swing.JRadioButton();
        Opc65 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        Opc66 = new javax.swing.JRadioButton();
        Opc67 = new javax.swing.JRadioButton();
        Opc68 = new javax.swing.JRadioButton();
        Opc69 = new javax.swing.JRadioButton();
        Opc70 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        Opc71 = new javax.swing.JRadioButton();
        Opc72 = new javax.swing.JRadioButton();
        Opc73 = new javax.swing.JRadioButton();
        Opc74 = new javax.swing.JRadioButton();
        Opc75 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        Opc76 = new javax.swing.JRadioButton();
        Opc77 = new javax.swing.JRadioButton();
        Opc78 = new javax.swing.JRadioButton();
        Opc79 = new javax.swing.JRadioButton();
        Opc80 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        Opc81 = new javax.swing.JRadioButton();
        Opc82 = new javax.swing.JRadioButton();
        Opc83 = new javax.swing.JRadioButton();
        Opc84 = new javax.swing.JRadioButton();
        Opc85 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Opc86 = new javax.swing.JRadioButton();
        Opc87 = new javax.swing.JRadioButton();
        Opc88 = new javax.swing.JRadioButton();
        Opc89 = new javax.swing.JRadioButton();
        Opc90 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        Opc91 = new javax.swing.JRadioButton();
        Opc92 = new javax.swing.JRadioButton();
        Opc93 = new javax.swing.JRadioButton();
        Opc94 = new javax.swing.JRadioButton();
        Opc95 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        Opc96 = new javax.swing.JRadioButton();
        Opc97 = new javax.swing.JRadioButton();
        Opc98 = new javax.swing.JRadioButton();
        Opc99 = new javax.swing.JRadioButton();
        Opc100 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("1. Sinceramente, creo que me exijo a mi mismo(a) exageradamente.");

        Opc1.setSelected(true);
        Opc1.setText("Nunca");

        Opc2.setText("Rara vez");

        Opc3.setText("A menudo");

        Opc5.setText("Siempre");

        Opc4.setText("Muy seguido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("2. A veces tengo la sensación de que las metas que persigo no me harán feliz.");

        Opc6.setSelected(true);
        Opc6.setText("Nunca");

        Opc7.setText("Rara vez");

        Opc8.setText("A menudo");

        Opc9.setText("Siempre");

        Opc10.setText("Muy seguido");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("3. Si no cumplí una promesa y me reclaman, me siento frustrado y tenso.");

        Opc11.setSelected(true);
        Opc11.setText("Nunca");

        Opc12.setText("Rara vez");

        Opc13.setText("A menudo");

        Opc14.setText("Siempre");

        Opc15.setText("Muy seguido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("4. Cuando trabajo en equipo necesito ser el lider para sentirme bien.");

        Opc16.setSelected(true);
        Opc16.setText("Nunca");

        Opc17.setText("Rara vez");

        Opc18.setText("A menudo");

        Opc19.setText("Siempre");

        Opc20.setText("Muy seguido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("5. A veces meto un tema de conversación para demostrar lo mucho que sé de él.");

        Opc21.setSelected(true);
        Opc21.setText("Nunca");

        Opc22.setText("Rara vez");

        Opc23.setText("A menudo");

        Opc24.setText("Siempre");

        Opc25.setText("Muy seguido");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("6. En las reuniones no puedo evitar tratar de llamar la atención de los demás.");

        Opc26.setSelected(true);
        Opc26.setText("Nunca");

        Opc27.setText("Rara vez");

        Opc28.setText("A menudo");

        Opc29.setText("Siempre");

        Opc30.setText("Muy seguido");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("7. A veces quiero mostrar ser otra persona para caer bien e interesar a la gente.");

        Opc31.setSelected(true);
        Opc31.setText("Nunca");

        Opc32.setText("Rara vez");

        Opc33.setText("A menudo");

        Opc34.setText("Siempre");

        Opc35.setText("Muy seguido");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("8. Definitivamente, soy una persona perfeccionista.");

        Opc36.setSelected(true);
        Opc36.setText("Nunca");

        Opc37.setText("Rara vez");

        Opc38.setText("A menudo");

        Opc39.setText("Siempre");

        Opc40.setText("Muy seguido");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("9. Sinceramente, prefiero que otros tomen las decisiones en mi lugar.");

        Opc41.setSelected(true);
        Opc41.setText("Nunca");

        Opc42.setText("Rara vez");

        Opc43.setText("A menudo");

        Opc44.setText("Siempre");

        Opc45.setText("Muy seguido");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("10. Me encanta comunicar mis logros a la personas aunque no me lo pregunten.");

        Opc46.setSelected(true);
        Opc46.setText("Nunca");

        Opc47.setText("Rara vez");

        Opc48.setText("A menudo");

        Opc49.setText("Siempre");

        Opc50.setText("Muy seguido");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("11. No puedo evitar sentirme bien cuando descubro un error en alguien más, aunque no se lo diga.");

        Opc51.setSelected(true);
        Opc51.setText("Nunca");

        Opc52.setText("Rara vez");

        Opc53.setText("A menudo");

        Opc54.setText("Siempre");

        Opc55.setText("Muy seguido");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("12. Tengo fantasias en las que alcanzo grandes logros y soy aplaudido por ellos.");

        Opc56.setSelected(true);
        Opc56.setText("Nunca");

        Opc57.setText("Rara vez");

        Opc58.setText("A menudo");

        Opc59.setText("Siempre");

        Opc60.setText("Muy seguido");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("13. Siento que aveces me manipulan usando mi ego, sin darme cuenta.");

        Opc61.setSelected(true);
        Opc61.setText("Nunca");

        Opc62.setText("Rara vez");

        Opc63.setText("A menudo");

        Opc64.setText("Siempre");

        Opc65.setText("Muy seguido");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("14.En muchos aspectos, siento que he dejado pasar la vida haciendo cosas que no disfruto.");

        Opc66.setSelected(true);
        Opc66.setText("Nunca");

        Opc67.setText("Rara vez");

        Opc68.setText("A menudo");

        Opc69.setText("Siempre");

        Opc70.setText("Muy seguido");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("15. Mi vida transcurre en mucha tensión.");

        Opc71.setSelected(true);
        Opc71.setText("Nunca");

        Opc72.setText("Rara vez");

        Opc73.setText("A menudo");

        Opc74.setText("Siempre");

        Opc75.setText("Muy seguido");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("16. La verdad, a veces me siento harto de trabajar tan arduamente.");

        Opc76.setSelected(true);
        Opc76.setText("Nunca");

        Opc77.setText("Rara vez");

        Opc78.setText("A menudo");

        Opc79.setText("Siempre");

        Opc80.setText("Muy seguido");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("17. A veces tengo la sensación de que necesito a los demás más que ellos a mi.");

        Opc81.setSelected(true);
        Opc81.setText("Nunca");

        Opc82.setText("Rara vez");

        Opc83.setText("A menudo");

        Opc84.setText("Siempre");

        Opc85.setText("Muy seguido");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("18. Algunas veces me porto amable, mientras que en mi interior siento odio, envidia o angustia.");

        Opc86.setSelected(true);
        Opc86.setText("Nunca");

        Opc87.setText("Rara vez");

        Opc88.setText("A menudo");

        Opc89.setText("Siempre");

        Opc90.setText("Muy seguido");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("19.A veces estoy seguro de que hacer en una situación, pero aún así pido consejo a alguien.");

        Opc91.setSelected(true);
        Opc91.setText("Nunca");

        Opc92.setText("Rara vez");

        Opc93.setText("A menudo");

        Opc94.setText("Siempre");

        Opc95.setText("Muy seguido");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("20. Creo que en mi vida las apariencias de los demás y la mia han sido muy importantes.");

        Opc96.setSelected(true);
        Opc96.setText("Nunca");

        Opc97.setText("Rara vez");

        Opc98.setText("A menudo");

        Opc99.setText("Siempre");

        Opc100.setText("Muy seguido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc1)
                .addGap(10, 10, 10)
                .addComponent(Opc2)
                .addGap(2, 2, 2)
                .addComponent(Opc3)
                .addGap(0, 0, 0)
                .addComponent(Opc4)
                .addGap(2, 2, 2)
                .addComponent(Opc5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc6)
                .addGap(10, 10, 10)
                .addComponent(Opc7)
                .addGap(2, 2, 2)
                .addComponent(Opc8)
                .addGap(0, 0, 0)
                .addComponent(Opc10)
                .addGap(2, 2, 2)
                .addComponent(Opc9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc11)
                .addGap(10, 10, 10)
                .addComponent(Opc12)
                .addGap(2, 2, 2)
                .addComponent(Opc13)
                .addGap(0, 0, 0)
                .addComponent(Opc15)
                .addGap(2, 2, 2)
                .addComponent(Opc14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc16)
                .addGap(10, 10, 10)
                .addComponent(Opc17)
                .addGap(2, 2, 2)
                .addComponent(Opc18)
                .addGap(0, 0, 0)
                .addComponent(Opc20)
                .addGap(2, 2, 2)
                .addComponent(Opc19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc21)
                .addGap(10, 10, 10)
                .addComponent(Opc22)
                .addGap(2, 2, 2)
                .addComponent(Opc23)
                .addGap(0, 0, 0)
                .addComponent(Opc25)
                .addGap(2, 2, 2)
                .addComponent(Opc24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc26)
                .addGap(10, 10, 10)
                .addComponent(Opc27)
                .addGap(2, 2, 2)
                .addComponent(Opc28)
                .addGap(0, 0, 0)
                .addComponent(Opc30)
                .addGap(2, 2, 2)
                .addComponent(Opc29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc31)
                .addGap(10, 10, 10)
                .addComponent(Opc32)
                .addGap(2, 2, 2)
                .addComponent(Opc33)
                .addGap(0, 0, 0)
                .addComponent(Opc35)
                .addGap(2, 2, 2)
                .addComponent(Opc34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc36)
                .addGap(10, 10, 10)
                .addComponent(Opc37)
                .addGap(2, 2, 2)
                .addComponent(Opc38)
                .addGap(0, 0, 0)
                .addComponent(Opc40)
                .addGap(2, 2, 2)
                .addComponent(Opc39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc41)
                .addGap(10, 10, 10)
                .addComponent(Opc42)
                .addGap(2, 2, 2)
                .addComponent(Opc43)
                .addGap(0, 0, 0)
                .addComponent(Opc45)
                .addGap(2, 2, 2)
                .addComponent(Opc44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc46)
                .addGap(10, 10, 10)
                .addComponent(Opc47)
                .addGap(2, 2, 2)
                .addComponent(Opc48)
                .addGap(0, 0, 0)
                .addComponent(Opc50)
                .addGap(2, 2, 2)
                .addComponent(Opc49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc51)
                .addGap(10, 10, 10)
                .addComponent(Opc52)
                .addGap(2, 2, 2)
                .addComponent(Opc53)
                .addGap(0, 0, 0)
                .addComponent(Opc55)
                .addGap(2, 2, 2)
                .addComponent(Opc54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc56)
                .addGap(10, 10, 10)
                .addComponent(Opc57)
                .addGap(2, 2, 2)
                .addComponent(Opc58)
                .addGap(0, 0, 0)
                .addComponent(Opc60)
                .addGap(2, 2, 2)
                .addComponent(Opc59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc61)
                .addGap(10, 10, 10)
                .addComponent(Opc62)
                .addGap(2, 2, 2)
                .addComponent(Opc63)
                .addGap(0, 0, 0)
                .addComponent(Opc65)
                .addGap(2, 2, 2)
                .addComponent(Opc64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc66)
                .addGap(10, 10, 10)
                .addComponent(Opc67)
                .addGap(2, 2, 2)
                .addComponent(Opc68)
                .addGap(0, 0, 0)
                .addComponent(Opc70)
                .addGap(2, 2, 2)
                .addComponent(Opc69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc71)
                .addGap(10, 10, 10)
                .addComponent(Opc72)
                .addGap(2, 2, 2)
                .addComponent(Opc73)
                .addGap(0, 0, 0)
                .addComponent(Opc75)
                .addGap(2, 2, 2)
                .addComponent(Opc74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc76)
                .addGap(10, 10, 10)
                .addComponent(Opc77)
                .addGap(2, 2, 2)
                .addComponent(Opc78)
                .addGap(0, 0, 0)
                .addComponent(Opc80)
                .addGap(2, 2, 2)
                .addComponent(Opc79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc81)
                .addGap(10, 10, 10)
                .addComponent(Opc82)
                .addGap(2, 2, 2)
                .addComponent(Opc83)
                .addGap(0, 0, 0)
                .addComponent(Opc85)
                .addGap(2, 2, 2)
                .addComponent(Opc84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc86)
                .addGap(10, 10, 10)
                .addComponent(Opc87)
                .addGap(2, 2, 2)
                .addComponent(Opc88)
                .addGap(0, 0, 0)
                .addComponent(Opc90)
                .addGap(2, 2, 2)
                .addComponent(Opc89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc91)
                .addGap(10, 10, 10)
                .addComponent(Opc92)
                .addGap(2, 2, 2)
                .addComponent(Opc93)
                .addGap(0, 0, 0)
                .addComponent(Opc95)
                .addGap(2, 2, 2)
                .addComponent(Opc94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Opc96)
                .addGap(10, 10, 10)
                .addComponent(Opc97)
                .addGap(2, 2, 2)
                .addComponent(Opc98)
                .addGap(0, 0, 0)
                .addComponent(Opc100)
                .addGap(2, 2, 2)
                .addComponent(Opc99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc1)
                    .addComponent(Opc2)
                    .addComponent(Opc3)
                    .addComponent(Opc4)
                    .addComponent(Opc5))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc6)
                    .addComponent(Opc7)
                    .addComponent(Opc8)
                    .addComponent(Opc10)
                    .addComponent(Opc9))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc11)
                    .addComponent(Opc12)
                    .addComponent(Opc13)
                    .addComponent(Opc15)
                    .addComponent(Opc14))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc16)
                    .addComponent(Opc17)
                    .addComponent(Opc18)
                    .addComponent(Opc20)
                    .addComponent(Opc19))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc21)
                    .addComponent(Opc22)
                    .addComponent(Opc23)
                    .addComponent(Opc25)
                    .addComponent(Opc24))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc26)
                    .addComponent(Opc27)
                    .addComponent(Opc28)
                    .addComponent(Opc30)
                    .addComponent(Opc29))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc31)
                    .addComponent(Opc32)
                    .addComponent(Opc33)
                    .addComponent(Opc35)
                    .addComponent(Opc34))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc36)
                    .addComponent(Opc37)
                    .addComponent(Opc38)
                    .addComponent(Opc40)
                    .addComponent(Opc39))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc41)
                    .addComponent(Opc42)
                    .addComponent(Opc43)
                    .addComponent(Opc45)
                    .addComponent(Opc44))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc46)
                    .addComponent(Opc47)
                    .addComponent(Opc48)
                    .addComponent(Opc50)
                    .addComponent(Opc49))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc51)
                    .addComponent(Opc52)
                    .addComponent(Opc53)
                    .addComponent(Opc55)
                    .addComponent(Opc54))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc56)
                    .addComponent(Opc57)
                    .addComponent(Opc58)
                    .addComponent(Opc60)
                    .addComponent(Opc59))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc61)
                    .addComponent(Opc62)
                    .addComponent(Opc63)
                    .addComponent(Opc65)
                    .addComponent(Opc64))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc66)
                    .addComponent(Opc67)
                    .addComponent(Opc68)
                    .addComponent(Opc70)
                    .addComponent(Opc69))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc71)
                    .addComponent(Opc72)
                    .addComponent(Opc73)
                    .addComponent(Opc75)
                    .addComponent(Opc74))
                .addGap(7, 7, 7)
                .addComponent(jLabel16)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc76)
                    .addComponent(Opc77)
                    .addComponent(Opc78)
                    .addComponent(Opc80)
                    .addComponent(Opc79))
                .addGap(7, 7, 7)
                .addComponent(jLabel17)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc81)
                    .addComponent(Opc82)
                    .addComponent(Opc83)
                    .addComponent(Opc85)
                    .addComponent(Opc84))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc86)
                    .addComponent(Opc87)
                    .addComponent(Opc88)
                    .addComponent(Opc90)
                    .addComponent(Opc89))
                .addGap(7, 7, 7)
                .addComponent(jLabel19)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc91)
                    .addComponent(Opc92)
                    .addComponent(Opc93)
                    .addComponent(Opc95)
                    .addComponent(Opc94))
                .addGap(7, 7, 7)
                .addComponent(jLabel20)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opc96)
                    .addComponent(Opc97)
                    .addComponent(Opc98)
                    .addComponent(Opc100)
                    .addComponent(Opc99))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Opc1;
    private javax.swing.JRadioButton Opc10;
    private javax.swing.JRadioButton Opc100;
    private javax.swing.JRadioButton Opc11;
    private javax.swing.JRadioButton Opc12;
    private javax.swing.JRadioButton Opc13;
    private javax.swing.JRadioButton Opc14;
    private javax.swing.JRadioButton Opc15;
    private javax.swing.JRadioButton Opc16;
    private javax.swing.JRadioButton Opc17;
    private javax.swing.JRadioButton Opc18;
    private javax.swing.JRadioButton Opc19;
    private javax.swing.JRadioButton Opc2;
    private javax.swing.JRadioButton Opc20;
    private javax.swing.JRadioButton Opc21;
    private javax.swing.JRadioButton Opc22;
    private javax.swing.JRadioButton Opc23;
    private javax.swing.JRadioButton Opc24;
    private javax.swing.JRadioButton Opc25;
    private javax.swing.JRadioButton Opc26;
    private javax.swing.JRadioButton Opc27;
    private javax.swing.JRadioButton Opc28;
    private javax.swing.JRadioButton Opc29;
    private javax.swing.JRadioButton Opc3;
    private javax.swing.JRadioButton Opc30;
    private javax.swing.JRadioButton Opc31;
    private javax.swing.JRadioButton Opc32;
    private javax.swing.JRadioButton Opc33;
    private javax.swing.JRadioButton Opc34;
    private javax.swing.JRadioButton Opc35;
    private javax.swing.JRadioButton Opc36;
    private javax.swing.JRadioButton Opc37;
    private javax.swing.JRadioButton Opc38;
    private javax.swing.JRadioButton Opc39;
    private javax.swing.JRadioButton Opc4;
    private javax.swing.JRadioButton Opc40;
    private javax.swing.JRadioButton Opc41;
    private javax.swing.JRadioButton Opc42;
    private javax.swing.JRadioButton Opc43;
    private javax.swing.JRadioButton Opc44;
    private javax.swing.JRadioButton Opc45;
    private javax.swing.JRadioButton Opc46;
    private javax.swing.JRadioButton Opc47;
    private javax.swing.JRadioButton Opc48;
    private javax.swing.JRadioButton Opc49;
    private javax.swing.JRadioButton Opc5;
    private javax.swing.JRadioButton Opc50;
    private javax.swing.JRadioButton Opc51;
    private javax.swing.JRadioButton Opc52;
    private javax.swing.JRadioButton Opc53;
    private javax.swing.JRadioButton Opc54;
    private javax.swing.JRadioButton Opc55;
    private javax.swing.JRadioButton Opc56;
    private javax.swing.JRadioButton Opc57;
    private javax.swing.JRadioButton Opc58;
    private javax.swing.JRadioButton Opc59;
    private javax.swing.JRadioButton Opc6;
    private javax.swing.JRadioButton Opc60;
    private javax.swing.JRadioButton Opc61;
    private javax.swing.JRadioButton Opc62;
    private javax.swing.JRadioButton Opc63;
    private javax.swing.JRadioButton Opc64;
    private javax.swing.JRadioButton Opc65;
    private javax.swing.JRadioButton Opc66;
    private javax.swing.JRadioButton Opc67;
    private javax.swing.JRadioButton Opc68;
    private javax.swing.JRadioButton Opc69;
    private javax.swing.JRadioButton Opc7;
    private javax.swing.JRadioButton Opc70;
    private javax.swing.JRadioButton Opc71;
    private javax.swing.JRadioButton Opc72;
    private javax.swing.JRadioButton Opc73;
    private javax.swing.JRadioButton Opc74;
    private javax.swing.JRadioButton Opc75;
    private javax.swing.JRadioButton Opc76;
    private javax.swing.JRadioButton Opc77;
    private javax.swing.JRadioButton Opc78;
    private javax.swing.JRadioButton Opc79;
    private javax.swing.JRadioButton Opc8;
    private javax.swing.JRadioButton Opc80;
    private javax.swing.JRadioButton Opc81;
    private javax.swing.JRadioButton Opc82;
    private javax.swing.JRadioButton Opc83;
    private javax.swing.JRadioButton Opc84;
    private javax.swing.JRadioButton Opc85;
    private javax.swing.JRadioButton Opc86;
    private javax.swing.JRadioButton Opc87;
    private javax.swing.JRadioButton Opc88;
    private javax.swing.JRadioButton Opc89;
    private javax.swing.JRadioButton Opc9;
    private javax.swing.JRadioButton Opc90;
    private javax.swing.JRadioButton Opc91;
    private javax.swing.JRadioButton Opc92;
    private javax.swing.JRadioButton Opc93;
    private javax.swing.JRadioButton Opc94;
    private javax.swing.JRadioButton Opc95;
    private javax.swing.JRadioButton Opc96;
    private javax.swing.JRadioButton Opc97;
    private javax.swing.JRadioButton Opc98;
    private javax.swing.JRadioButton Opc99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
